import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./provides";
import Header from "@/Components/shared/Header";
import Footer from "@/Components/shared/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <Providers>
          <Header />
          {/* <div className="pt-14"> */}
          {children}
          <Footer />
          {/* </div> */}
        </Providers>
      </body>
    </html>
  );
}
